### ISSUE TITLE
aeriki panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by dingbb** [aeraki-mesh/aeraki#285] opened 2022-11-25 09:00 UTC
**environmental information (Aeraki+Nacos)**
k8s version: v1.20.10
istio version: 1.13.4
Aeraki version: 1.1.2
knative

**Describe the bug**
 Create through interface MetaRouter err
Error from server (InternalError): error when creating "3.yaml": Internal error occurred: failed calling webhook "validation.aeraki.io": Post "https://aeraki.istio-system.svc:443/validate?timeout=10s": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "aeraki.com")

 Aeraki pod restart and runtime error: invalid memory address or nil pointer dereference

Aeraki Panic err:
022-11-25T08:09:24.239494Z debug xds-server receive event from push chanel : update
2022-11-25T08:09:25.239641Z info debounce stable[1] 20: 1.000107951s since last event, 2.690947722s since last debounce
2022-11-25T08:09:25.239944Z debug xds-server no meta router for : synthetic-thrift-sample-server
2022-11-25T08:09:25.240034Z debug xds-server no meta router for : aeraki-com-shopline-devops-shoplinestartermeshdemo-api-remoteapi-1-0-0
2022-11-25T08:09:25.240091Z debug xds-server no meta router for : aeraki-com-shopline-devops-shoplinestartermeshdemo-api-meshdubboapi-1-0-0
2022-11-25T08:09:25.240146Z debug xds-server no meta router for : aeraki-org-apache-dubbo-samples-basic-api-secondservice
2022-11-25T08:09:25.240199Z debug xds-server find meta router ：test-metaprotocol-dubbo-route for : aeraki-org-apache-dubbo-samples-basic-api-demoservice
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc8 pc=0x1e4e25d]

goroutine 797 [running]:
github.com/aeraki-mesh/aeraki/pkg/model.GetHashPolicy(0x2b7cb71, {0x0, 0x0})
 /Users/huabingzhao/workspace/aeraki/pkg/model/utils.go:57 +0x5d
github.com/aeraki-mesh/aeraki/pkg/xds.(*CacheMgr).constructAction(0xc000d4d6d8, 0xc00194b310, 0xc000ff7170, 0xc000d4d760)
 /Users/huabingzhao/workspace/aeraki/pkg/xds/cache_mgr.go:257 +0x17f
github.com/aeraki-mesh/aeraki/pkg/xds.(*CacheMgr).constructRoute(0xc0007d0ea0, 0xc0008ccd80, 0xc00194b310, 0x0, 0x4)
 /Users/huabingzhao/workspace/aeraki/pkg/xds/cache_mgr.go:227 +0x12d
github.com/aeraki-mesh/aeraki/pkg/xds.(*CacheMgr).generateMetaRoutes(0xc0004c0640, {0xc000e20000, 0x7c, 0x2b7cfa9})
 /Users/huabingzhao/workspace/aeraki/pkg/xds/cache_mgr.go:197 +0x80a
github.com/aeraki-mesh/aeraki/pkg/xds.(*CacheMgr).updateRouteCache(0xc00063ea00)
 /Users/huabingzhao/workspace/aeraki/pkg/xds/cache_mgr.go:133 +0x18d
github.com/aeraki-mesh/aeraki/pkg/xds.(*CacheMgr).mainLoop.func1()
 /Users/huabingzhao/workspace/aeraki/pkg/xds/cache_mgr.go:94 +0x2f
github.com/zhaohuabing/debounce.(*Debouncer).run(0xc000fe8780)
 /Users/huabingzhao/go/pkg/mod/github.com/zhaohuabing/debounce@v1.0.0/debounce.go:106 +0x35a
created by github.com/zhaohuabing/debounce.New
 /Users/huabingzhao/go/pkg/mod/github.com/zhaohuabing/debounce@v1.0.0/debounce.go:53 +0xf5

**aeraki start error**
2022-11-25T08:45:07.400834Z	error	namespace-controller	failed to create configMap: Internal error occurred: failed calling webhook "config.webhook.serving.knative.dev": Post "https://webhook.knative-serving.svc:443/config-validation?timeout=10s": no endpoints available for service "webhook"

**Screenshots**
![image](https://user-images.githubusercontent.com/29624378/203940780-6be7f81b-2fc3-4d75-a35a-6bf90594b293.png)
![image](https://user-images.githubusercontent.com/29624378/203940840-0698d39e-3f67-4a8f-8c5f-11b64674b705.png)
![image](https://user-images.githubusercontent.com/29624378/203940890-ed94d650-656a-4bb9-9a9f-57f4da1f4ca2.png)
![image](https://user-images.githubusercontent.com/29624378/203941310-8f95773e-ef18-4b3c-b8e8-f83c2bcb6e1a.png)
![image](https://user-images.githubusercontent.com/29624378/203941460-19564e0b-bc92-42b7-9cf1-c85ff399fbce.png)
![image](https://user-images.githubusercontent.com/29624378/203944271-f90d3e0e-e022-453f-b5a2-79dbc13a1a32.png)

**Additional context**

**Comment by zhaohuabing** [comment] 2022-11-25 11:42
The nil pointer issue has been fixed by #286 

I can't reproduce the webhook error "crypto/rsa: verification error" , if you still have this problem, you could raise other issue to tract it.

**Closed by zhaohuabing** 2022-11-25 11:42 UTC
